name: Build Rust Apps

on:
  schedule:
    # Run at 00:00 on the first of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Read repository list (Linux)
      if: runner.os == 'Linux'
      run: |
        while IFS= read -r repo; do
          repo=$(echo $repo | tr -d '\r')
          echo "Processing $repo"
          git clone $repo
          repo_name=$(basename "$repo" .git)
          cd "$repo_name"
          echo "Building $repo_name"
          cargo build --release --target-dir "../build-artifacts/${{ matrix.os }}/$repo_name"
          cd ..
        done < repos.txt

    - name: Read repository list (Windows)
      if: runner.os == 'Windows'
      run: |
        Get-Content repos.txt | ForEach-Object {
          $repo = $_.Trim()
          Write-Host "Processing $repo"
          git clone $repo
          $repo_name = $repo -replace '.*/(.*)\.git', '$1'
          Set-Location $repo_name
          Write-Host "Building $repo_name"
          cargo build --release --target-dir "../build-artifacts/${{ matrix.os }}/$repo_name"
          Set-Location ..
        }

    - name: Archive full release directory (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p full-release/${{ matrix.os }}
        cp -r build-artifacts/${{ matrix.os }}/* full-release/${{ matrix.os }}/
        cd full-release/${{ matrix.os }}
        zip -r "../../full-release-ubuntu-latest.zip" .
        # Print the contents of the directory
        echo "Contents of full-release directory:"
        ls -al

    - name: Archive full release directory (Windows)
      if: runner.os == 'Windows'
      run: |
        $fullReleasePath = "full-release/${{ matrix.os }}"
        if (-Not (Test-Path -Path $fullReleasePath)) {
          New-Item -ItemType Directory -Path $fullReleasePath -Force
        }
        Copy-Item -Path "build-artifacts/${{ matrix.os }}/*" -Destination $fullReleasePath -Recurse
        Compress-Archive -Path "$fullReleasePath/*" -DestinationPath "full-release-windows-latest.zip"
        # Print the contents of the directory
        Write-Host "Contents of full-release directory:"
        Get-ChildItem -Path $fullReleasePath -Recurse

    - name: Archive built binaries (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p build-artifacts/${{ matrix.os }}
        for repo in $(ls -d */); do
          repo_name=$(basename "$repo")
          echo "Checking for release directory in $repo_name"
          if [ -d "$repo/release" ]; then
            echo "Copying binaries from $repo/target/release"
            mkdir -p "build-artifacts/${{ matrix.os }}/$repo_name"
            #cp -r "$repo/target/release/"* "build-artifacts/${{ matrix.os }}/$repo_name/"#stupid dont need folder anymore
            cp "$repo/release/"* "build-artifacts/${{ matrix.os }}/"
          else
            echo "Release directory not found for $repo_name"
          fi
        done
        cd build-artifacts/${{ matrix.os }}
        # Print the contents of the directory
        echo "Contents of build-artifacts directory:"
        ls -al
        zip -r "../../binaries-ubuntu-latest.zip" ./
        

    - name: Archive built binaries (Windows)
      if: runner.os == 'Windows'
      run: |
        $artifactsPath = "build-artifacts/${{ matrix.os }}"
        if (-Not (Test-Path -Path $artifactsPath)) {
          New-Item -ItemType Directory -Path $artifactsPath -Force
        }
        Get-ChildItem -Path $artifactsPath | Where-Object { $_.PSIsContainer } | ForEach-Object {
          $repo_name = $_.Name
          #Write-Host "Checking for release directory in $repo_name"
          if (Test-Path "$artifactsPath/$repo_name/release") {
            #Write-Host "Copying binaries from $repo_name/release"
            $dest_path = "$artifactsPath/$repo_name"
            New-Item -ItemType Directory -Path $dest_path -Force
            #Copy-Item "$artifactsPath/$repo_name/release/*" -Destination $dest_path -Recurse#no recurse so,binaries only
            Copy-Item "$artifactsPath/$repo_name/release/*.exe" -Destination $dest_path
            Compress-Archive -Path "$dest_path/*.exe" -DestinationPath "binaries-windows-latest.zip"
          } else {
            Write-Host "Release directory not found for $repo_name.Do full release."
            Compress-Archive -Path "$artifactsPath/*" -DestinationPath "binaries-windows-latest.zip"
          }
        }
        #Compress-Archive -Path "$artifactsPath/*" -DestinationPath "binaries-windows-latest.zip"#stupid ai gt all
        # Print the contents of the directory,stupid ai debug use.
        #Write-Host "Contents of build-artifacts directory:"
        #Get-ChildItem -Path $artifactsPath -Recurse

    - name: Upload full release artifact (Linux)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: full-release-ubuntu-latest
        path: full-release-ubuntu-latest.zip

    - name: Upload full release artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: full-release-windows-latest
        path: full-release-windows-latest.zip

    - name: Upload binaries artifact (Linux)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: binaries-ubuntu-latest
        path: binaries-ubuntu-latest.zip

    - name: Upload binaries artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: binaries-windows-latest
        path: binaries-windows-latest.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download full release artifacts (Linux)
      uses: actions/download-artifact@v3
      with:
        name: full-release-ubuntu-latest
        path: ./full-release/linux

    - name: Download full release artifacts (Windows)
      uses: actions/download-artifact@v3
      with:
        name: full-release-windows-latest
        path: ./full-release/windows

    - name: Download binaries artifacts (Linux)
      uses: actions/download-artifact@v3
      with:
        name: binaries-ubuntu-latest
        path: ./binaries/linux

    - name: Download binaries artifacts (Windows)
      uses: actions/download-artifact@v3
      with:
        name: binaries-windows-latest
        path: ./binaries/windows
    
    - name: Install GitHub CLI
      uses: actions4gh/setup-gh@v1.0.2

    - name: Generate Release Tag
      id: generate_tag
      run: |
          # Generate a unique tag using the current date and time
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Create Release using GitHub CLI
      run: |
          gh release create $TAG ./full-release/linux/full-release-ubuntu-latest.zip ./full-release/windows/full-release-windows-latest.zip
      env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}

    - name: Upload Linux Binaries
      run: |
          gh release upload $TAG ./binaries/linux/binaries-ubuntu-latest.zip
      env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}

    - name: Upload Windows Binaries
      run: |
          gh release upload $TAG ./binaries/windows/binaries-windows-latest.zip
      env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.TAG }}
